import './globals.css'
import {Footer} from "./_component/footer";
import {Header} from "./_component/header";
import { ToastContainer } from 'react-toastify'

export const metadata = {
  title: 'amlak',
  description: 'Generated by Next.js',
}


export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
          <body>{children}</body>

    </html>
  )
}
